@startuml

scale max 600 height

' left to right direction

' top to bottom direction

' rectangle Developers #line.dotted {
    actor "System Developer" as SD
    actor "Knowledge Engineer" as KE
    actor "AI Developer" as AID
' }

rectangle "System" as System {
    ' rectangle "UI/Client" as UI1
    ' rectangle "UI/Client 2" as UI2
    ' rectangle "UI/Client 3" as UI3
    ' rectangle Extractor
    ' cloud "Server" {
    '     rectangle Service
    '     database Storage
    ' }
}

' Users -[hidden]right- System

' Us -down-> UI1
' Ub -down-> UI2: browse
' Um -down-> UI3: modify

' Us -[hidden]right- Ub
' Ub -[hidden]right- Um

' Internet <-- Extractor: craw & extract
' Extractor --> Service

' UI1 -[hidden]right- UI2
' UI2 -[hidden]right- UI3

' UI1 -down-> Service
' UI2 -down-> Service
' UI3 -down-> Service
' Service -> Storage

SD -> System: develop \nplatform & service
System <-right- KE: develop \nknowledge representation
System <-right- AID: develop \nAI algorithms

KE -[hidden]down- AID

@enduml