@startuml

scale max 600 width

class "Extractor" as E {
    crawl()
    parse()
    extract()
}

class "Knowledge Storage" as S {
    read()
    insert()
    update()
    delete()
}

class "Service" as Sv {
    getRepresentationSchema()
    searchKnowledge()
    getRelatedKnowledge()
    insertKnowledge()
    updateKnowledge()
    deleteKnowledge()
}

package "UI" as UI {
    class Searching {
        search()
    }
    class Displaying {
        render()
        display()
    }
    class Modifying {
        modify()
    }

    ' Searching -[hidden]do- Displaying
    ' Displaying -[hidden]do- Modifying
}

E -> Sv
Sv --> S

Searching --> Sv 
Displaying --> Sv 
Modifying --> Sv 

@enduml