@startuml

class "Extractor" as E 

class "Knowledge Base" as S

class "Service" as Sv

package "UI" as UI {
    class Searching
    class Displaying
    class Modifying

    ' Searching -[hidden]do- Displaying
    ' Displaying -[hidden]do- Modifying
}

E -> Sv
Sv --> S

Searching --> Sv 
Displaying --> Sv 
Modifying --> Sv 

@enduml