@startuml

' rectangle Users #line.dotted {
    actor "User" as Us
    ' actor "User 2" as Ub
    ' actor "User 3" as Um
' }

rectangle "System" as System {
    ' rectangle UI
    ' cloud {
        ' rectangle Service
        ' database Storage
    ' }
}

' rectangle Extractor

' rectangle "Knowledge Source" #line.dotted {
    cloud WWW
' }

' Users -[hidden]down- System

' Us -down-> UI: search
' Ub -down-> UI: browse
' Um -down-> UI: modify

' Us -[hidden]right- Ub
' Ub -[hidden]right- Um

' Internet <-- Extractor: craw & extract
' Extractor --> Service

' UI -right-> Service
' Service -> Storage

Us -> System: search/modify
System <- WWW: crawl&extract 

@enduml