@startuml

scale 2

' rectangle Users #line.dotted {
    actor "User" as Us  <<actor>>
    ' actor "User 2" as Ub
    ' actor "User 3" as Um
' }

rectangle "System \nunder \nanalysis" as System {
    ' rectangle UI
    ' cloud {
        ' rectangle Service
        ' database Storage
    ' }
}

' rectangle Extractor

' rectangle "Knowledge Source" #line.dotted {
    ' cloud WWW
' }
(WWW) <<external>>

' Users -[hidden]down- System

' Us -down-> UI: search
' Ub -down-> UI: browse
' Um -down-> UI: modify

' Us -[hidden]right- Ub
' Ub -[hidden]right- Um

' Internet <-- Extractor: craw & extract
' Extractor --> Service

' UI -right-> Service
' Service -> Storage

Us -> System: search/\nmodify
System <- (WWW): crawl&\nextract 

@enduml