@startuml

scale max 600 width

actor User
participant UI
participant "Representation Service" as Representation_Service
database Storage

autonumber

User -> UI: start searching
activate UI
UI -> Representation_Service: send request
activate Representation_Service
Representation_Service -> Storage: query DB
activate Storage

Representation_Service <- Storage: returns data
deactivate Storage
UI <- Representation_Service: returns unified data
deactivate Representation_Service
User <- UI: render and display
deactivate UI

@enduml