SELECT * FROM Product;
SELECT * FROM Store;
SELECT * FROM Supplier;
SELECT * FROM DateDim;

select SUPPLIER_ID, WM_CONCAT(DISTINCT SUPPLIER_NAME) FROM MASTERDATA group by SUPPLIER_ID;
select SUPPLIER_ID, COUNT(DISTINCT SUPPLIER_NAME) FROM MASTERDATA group by SUPPLIER_ID;


SELECT * FROM dual;