SELECT count(*) FROM Product;
SELECT * FROM Store;
SELECT * FROM Supplier;
SELECT count(*) FROM Customer;
SELECT count(*) FROM DateDim;
SELECT * FROM Sales;
SELECT count(*) FROM Sales;

select SUPPLIER_ID, WM_CONCAT(DISTINCT SUPPLIER_NAME) FROM MASTERDATA group by SUPPLIER_ID;
select SUPPLIER_ID, COUNT(DISTINCT SUPPLIER_NAME) FROM MASTERDATA group by SUPPLIER_ID;


SELECT * FROM dual;